### ISSUE TITLE
Duplicate Recording's

### ISSUE THREAD

**Issue by longsack** [beaston02/ChaturbateRecorder#19]
Just noticed a few of the models are producing duplicate recordings... one starts, another stats like a minute later.  Any thoughts?  Is this a bug?

**Comment by beaston02** [comment]
Are you on the latest version? I know that was an issue on an earlier version, but it should be fixed now. Also, you're sure they are duplicates and not just short shows, ie: the model was going on and offline, having issues with the camera, or going in and out of free chat?

**Comment by francisuk1989** [comment]
@longsack 
dos it sounds like this error? https://github.com/beaston02/CAM4Recorder/issues/2

**Comment by longsack** [comment]
using the most current version.  no on the short shows, it will sometimes record the same show twice starting at say 23.10.12 then another at 23.11.35 then run each one for 30 or more minutes.

**Comment by longsack** [comment]
about 1/2 way through a new review, it seems that once I removed my login/password that the duplicates have stopped.  Will just add by hand.

**Comment by longsack** [comment]
Never mind, still doing it... example i have video of the same model starting at 01.53.08 that runs for 43 mins.  Another (same model) starting at 01.54.14 that runs for 41 minutes.  both same date.  Any idea?

**Comment by longsack** [comment]
Not sure if it means anything, I do get this error at random points...

naException in thread Thread-33:adelia', 'sarahbroke', 'laurabigtits', 'stephie_martinez', 'anielli69', 'jennylove52']
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/recorders/chaturbate/ChaturbateRecorder.py", line 70, in startRecording
    os.rename(filePath, finishedDir+'/'+filePath.rsplit['/',1][0])
TypeError: 'builtin_function_or_method' object is not subscriptable

[2017-10-02 20:03:19] 44 model(s) are being recorded. Next check in 3 seconds

**Comment by longsack** [comment]
francisuk1989 yes that seems to be it, what was/is the fix action I can take?

**Comment by longsack** [comment]
Another example of the error I seem to get a lot of... maybe this is the cause of the double/triple video downloads....

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/livestreamer/plugins/stream.py", line 73, in _get_streams
    streams = cls(self.session, urlnoproto, **params)
  File "/usr/local/lib/python3.6/site-packages/livestreamer/stream/hls.py", line 279, in parse_variant_playlist
    res = session_.http.get(url, exception=IOError, **request_params)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/livestreamer/plugin/api/http_session.py", line 135, in request
    raise err
OSError: Unable to open URL: https://edge105.stream.highwebmedia.com/live-edge/shamiz-sd-cca31776b544d830785892fe528ae44f6022cfa5afe51e012375dfe3e32a1f10_fast_aac/playlist.m3u8 (404 Client Error: Not Found for url: https://edge105.stream.highwebmedia.com/live-edge/shamiz-sd-cca31776b544d830785892fe528ae44f6022cfa5afe51e012375dfe3e32a1f10_fast_aac/playlist.m3u8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/recorders/chaturbate/ChaturbateRecorder.py", line 38, in startRecording
    streams = session.streams("hlsvariant://{}".format(result['hls_source'].rsplit('?')[0]))
  File "/usr/local/lib/python3.6/site-packages/livestreamer/session.py", line 355, in streams
    return plugin.streams(**params)
  File "/usr/local/lib/python3.6/site-packages/livestreamer/plugin/plugin.py", line 227, in streams
    ostreams = self._get_streams()
  File "/usr/local/lib/python3.6/site-packages/livestreamer/plugins/stream.py", line 75, in _get_streams
    raise PluginError(err)

**Comment by Qwatuz** [comment]
Do you by chance have the same model 2 or more times in your wanted.txt?

**Comment by longsack** [comment]
no sent them through a text editor and removed any duplicates a long time ago. now I use a web based form that checks for duplicates if its already in my wanted list it rejects the entry.

**Comment by beaston02** [comment]
Sorry for the the slow reply. I gave myself a break from all this while I was dealing with some other things. 

Is this still an issue? 

@Qwatuz , that was a good thought, however the script will handle duplicates int he list with no problem. It wont modify the wanted file, but when it reads the file into a variable, it will remove any duplicate names so each name only appears once, so duplicated names wont cause duplicate recordings. 

Let me know if you are still seeing the duplicates, and how often you see them and Ill see if I cant figure out a solution. I was hoping I had this one fixed!! haha.

**Comment by longsack** [comment]
testing newest version now, will let you know.

**Comment by longsack** [comment]
![capture](https://user-images.githubusercontent.com/31635078/31976224-d9e02ef6-b8fb-11e7-827d-02a5b966eb5d.JPG)

attached a screenshot still happening.... as you can see amialovesall19 stated twice within 1 minute.
amyfox_cb also...

its not throwing errors in ssh.

**Comment by longsack** [comment]
it just opens and then opens another one for a reason I don't know.... debian 7, using python3.6

**Comment by beaston02** [comment]
Thank you for the update. I just set it to check the list to see if the model is recording immediately before starting a recording. Im really not sure whats causing it, so this is kind of a shot in the dark, but lets see if it works...

**Comment by longsack** [comment]
your the best, will give a try and see again... will let u know.

**Comment by longsack** [comment]
checking now... don't see any duplicates as of about 10 mins of running... throwing some errors...

KeyboardInterrupt
Exception in thread Thread-93:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 73, in startRecording
    recording.remove(model)
ValueError: list.remove(x): x not in list

Exception in thread Thread-58:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 73, in startRecording
    recording.remove(model)
ValueError: list.remove(x): x not in list

Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 73, in startRecording
    recording.remove(model)
ValueError: list.remove(x): x not in list

Exception in thread Thread-63:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 73, in startRecording
    recording.remove(model)
ValueError: list.remove(x): x not in list

Exception in thread Thread-52:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 73, in startRecording
    recording.remove(model)
ValueError: list.remove(x): x not in list

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 73, in startRecording
    recording.remove(model)
ValueError: list.remove(x): x not in list

Exception in thread Thread-198:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 73, in startRecording
    recording.remove(model)
ValueError: list.remove(x): x not in list

**Comment by longsack** [comment]
just got a duplicate running... 19honeysuckle started at 21.34 and again at 37 watching both of them record now.

**Comment by beaston02** [comment]
I just posted a few updates. After each one, I noticed something else worth trying.... lol.  Sorry about that!

I noticed the models names werent being converted to lowercase when gathered, which amy have caused troubles, so I fixed that (I dont believe this was the issue however, since the model you just mentioned is already lowercase). 

I also used a kind of weird way to build the list of models to start recording. I dont know that it would cause the problem, but I changed it to a way that Im now more familiar with. Im still learning, and the code was something I must have gotten from google some time ago.

Thank you for reporting back! Let me know if this helps!

**Comment by longsack** [comment]
giving it a try, will probably come back tomorrow and let you know, late here.

**Comment by longsack** [comment]
ya, still doing it... :(... thank you so much for the work on this...

here is what it's showing me... in bash.
', 'loverosella', 'xlatinahotx', 'dropitella', 'gang_b_team', 'lexilow', 'kellymun', 'annysmiles', 'new_cindy', 'madyjewels', 'sunnygirrrl', 'hotfallingdevil', 'melisawood', 'kittyobsce^CException in thread Thread-216:ks', 'little_sophie_']
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 72, in startRecording
    recording.remove(model)
ValueError: list.remove(x): x not in list

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 72, in startRecording
    recording.remove(model)
ValueError: list.remove(x): x not in list

Exception in thread Thread-213:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateRecorder.py", line 72, in startRecording
    recording.remove(model)
ValueError: list.remove(x): x not in list

^CTraceback (most recent call last):
  File "ChaturbateRecorder.py", line 137, in <module>
    getOnlineModels()
  File "ChaturbateRecorder.py", line 109, in getOnlineModels
    wantedModels = [m for m in (list(set(wanted))) if m in online and m not in recording]
  File "ChaturbateRecorder.py", line 109, in <listcomp>
    wantedModels = [m for m in (list(set(wanted))) if m in online and m not in recording]
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/local/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/local/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/local/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 39, in _python_exit
    t.join()
^C  File "/usr/local/lib/python3.6/threading.py", line 1056, in join
^C  File "/usr/local/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock

**Comment by beaston02** [comment]
are you still getting duplicates, or just the error?

I just updated it, which should eliminate that error.

**Comment by longsack** [comment]
Still getting the dups...just posted the error if it was of any help.

**Comment by longsack** [comment]
Changed whole system Debian 7 to 8 and upgraded... still same issue, seems to record double a lot still.... just fyi :)

**Comment by longsack** [comment]
Switched from python 3.6 to 3.5 and the duplicates have gone away it seems...so maybe a 3.6 issue?

**Comment by longsack** [comment]
The problem came back... i think this is an issue with having pyhton2.7, 3.5 and 3.6 on the system perhaps, maybe not installed correctly?

**Comment by longsack** [comment]
only running 2.7 and 3.5 now, still an issue.  I had Debian 7 system, moved over to Ubuntu 16.04.  Removed 3.6 with the hope it would correct the issue, nope! :(
